import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/navbar/header";
import Footer from "@/components/layout/footer/footer";
import { QueryProvider } from "@/providers/query-provider";
import { AuthProvider } from "@/context/AuthContext";

import { Suspense } from "react";
import TopLoader from "@/components/ui/top-loader";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "YDM Logistics",
  description: "Generated by YDM Logistics",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <QueryProvider>
            <Header />
            <main className="min-h-screen">{children}</main>
            <Footer />
          </QueryProvider>
        </AuthProvider>
        <QueryProvider>
          <Suspense fallback={null}>
            <TopLoader />
          </Suspense>
          <Header />
          <main className="min-h-screen">{children}</main>
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
